# Generated by Django 5.1.7 on 2025-04-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='image',
            new_name='photo',
        ),
    ]
